---
- name: Deploy Java package on Apache Tomcat locally
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    java_package_name: com.mypru
    java_package_version: "0.0.1-SNAPSHOT"
    tomcat_bin_dir: "/opt/tomcat/bin"
    tomcat_webapps_dir: "/opt/tomcat/webapps"
    github_token: "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"

  tasks:
    - name: Ensure Tomcat bin directory exists
      file:
        path: "{{ tomcat_bin_dir }}"
        state: directory
        mode: '0755'

    - name: Stop Tomcat
      command: "{{ tomcat_bin_dir }}/shutdown.sh"
      ignore_errors: true
      async: 300
      poll: 0

    - name: Wait for Tomcat to stop
      wait_for:
        path: "{{ tomcat_bin_dir }}/shutdown.sh"
        state: absent

    - name: Download Java package from GitHub release
      shell: gh release download java-maven5-1.1 --repo pravesh-77/publish-java-package-with-maven --pattern "*.war" --dir "{{ tomcat_webapps_dir }}"
      environment:
        GITHUB_TOKEN: "{{ GITHUB_Token }}"
      register: download_result

    - name: Start Tomcat
      command: "{{ tomcat_bin_dir }}/startup.sh"
